liamship/config/routes.rb
Rails.application.routes.draw do

  root 'users#new'

  resources :games do
    resources :shots, shallow: true, only: [:new, :create]
  end

  resources :users, only: [:new, :create, :show]
  resources :sessions

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/games/:id/turn' => 'games#turn'
end

liamship/app/models/user.rb
class User < ApplicationRecord
  has_many :shots
  has_many :games
  has_many :game_ships

  validates :name, presence: true, uniqueness: true
  validates :password, length: {minimum: 6}  
  has_secure_password

end

liamship/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:player_id] = @user.id
      redirect_to(@user)
    else
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :password)
  end


end

liamship/app/helpers/users_helper.rb
module UsersHelper
  def logged_in?
    User.exists?(session[:user_id])
  end

  def current_user
    User.find(session[:user_id])
  end
end

liamship/app/views/users/new.html.erb
<h1> Welcome To Liam-Ship! </h1>
<br>
<h2>What is your name, Padawan?</h2>
<div class='signup-login-form'>
  <%= form_for @user do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>

    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.submit %>
  <%end%>
</div>

liamship/app/views/users/show.html.erb
<h1> <%= @user.name %> </h1>

<%= link_to 'create a new game', new_game_path %>
<%= link_to 'active games', '/games#index' %>