liamship/config/routes.rb
Rails.application.routes.draw do

  root 'users#new'

  resources :games do
    resources :shots, shallow: true, only: [:new, :create]
  end

  resources :users, only: [:new, :create, :show]
  resources :sessions

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/games/:id/turn' => 'games#turn'
end

liamship/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Liamship</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <nav class="main-nav">
    <ul id="navbar-ul">
      <li id="navbar-list"><%= link_to 'Games', games_path, class: 'games-link' %></li>
      <% if !logged_in? %>
        <li id="navbar-list-right"><%= link_to 'User Register', new_user_path, class: 'navbar-link' %></li>
        <li id="navbar-list-right"><%= link_to 'User Login', new_session_path, class: 'navbar-link' %></li>
      <% else %>
        <li id="navbar-list-right"><%= link_to 'Logout', session_path(current_user),
              method: :delete,
              data: { confirm: 'Are you sure you want to logout?' }, class: 'navbar-link' %></li>
        <li id="navbar-list-right"><%= link_to "#{current_user.name}", user_path(current_user), class: 'navbar-link' %></li>
      <% end %>
    </ul>
  </nav>
  <br>
    <div class="container">

      <%= yield %>
    </div>
  </body>
</html>