liamship/config/routes.rb
Rails.application.routes.draw do

  root 'users#new'

  resources :games do
    resources :shots, shallow: true, only: [:new, :create]
  end

  resources :users, only: [:new, :create, :show]
  resources :sessions

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/games/:id/turn' => 'games#turn'
end

liamship/app/models/game.rb
class Game < ApplicationRecord
  has_many :shots
  has_many :game_ships
  belongs_to :player_1, class_name: "User"
  belongs_to :player_2, class_name: "User", required: false
  belongs_to :winner, class_name: "User", required: false

  validates :player_1_id, presence: true

  def winner?
    game_ships_1 = dead_game_ships(self.player_1_id)
    game_ships_2 = dead_game_ships(self.player_2_id)
    if game_ships_1.count == 5
      self.winner_id = self.player_2_id
      return true
    elsif game_ships_2.count == 5
      self.winner_id = self.player_1_id
      return true
    else
      return false
    end
  end

  def dead_game_ships(player_id)
    ships = []
    possible_ships = GameShip.where(game_id: self.id, player_id: player_id)
    possible_ships.each do |ship|
      if ship.current_lives <= 0
        ships << ship
      end
    end
    ships
  end

end

liamship/app/controllers/games_controller.rb
require 'json'

class GamesController < ApplicationController

  def index
    @games = Game.where(player_2_id: nil)
  end


  def show
    @game = Game.find(params[:id])
    @coordinate = Coordinate.new
    if @game.player_2_id == nil && current_user.id != @game.player_1_id
      @game.player_2_id = current_user.id
      @game.save
    end
    if @game.winner?
      render 'winner'
    end
    # if current_user.id != @game.player_1_id || current_user.id != @game.player_2_id
    #   redirect_to "index"
    # end
    @current_player = session[:player_id]
    @enemy_player = enemy_player(@game.id, session[:player_id])
    @all_shots = Shot.where(game_id: @game.id)
  end

  def turn
    @game = Game.find(params[:id])
    whose_turn?(@game.id) == session[:player_id] ? @player = true : @player = false
    # binding.pry
    render :json => @player
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(player_1_id: session[:player_id])
    if @game.save
      session[:player_id] = current_user.id
      redirect_to(@game)
    else
      render 'new'
    end
  end

  def whose_turn?(game_id)
    game = Game.find_by(id: game_id)
    p1_shots = Shot.where(game_id: game_id, player_id: game.player_1_id)
    p2_shots = Shot.where(game_id: game_id, player_id: game.player_2_id)
    # binding.pry
    p p1_shots.count
    p p2_shots.count

    if p1_shots.count == 0 && p2_shots.count == 0
      return game.player_1_id
    elsif p1_shots.count > p2_shots.count
      return game.player_2_id
    elsif p1_shots.count == p2_shots.count
      return game.player_1_id
    end
  end

  def enemy_player(game_id, player_id)
    game = Game.find_by(id: game_id)
    if player_id == game.player_1_id
      return enemy_id = game.player_2_id
    else
      return enemy_id = game.player_1_id
    end
  end

end

liamship/app/helpers/games_helper.rb
module GamesHelper

end

liamship/app/views/games/hit.html.erb
<div class='hitmess'><h1> You Got a Hit </h1></div>

liamship/app/views/games/index.html.erb
<br><br><br><br><br><br>
<div class="list"><h1>Find your Opponent, and sink them</h1>

<% if @games %>
<% @games.each do |game|%>
  <li><a href="games/<%=game.id%>">Join Game with <%=game.player_1.name%></a></li><br>
<%end%>
<%end%>
</div>

liamship/app/views/games/miss.html.erb
<div class='missmess'><h1>Aw Shucks, you missed </h1></div>

liamship/app/views/games/new.html.erb
<h1> Create a Game, Padawan </h1>
<%= form_for(@game) do |f| %>
  <%= f.submit "New Game" %>
<% end %>

liamship/app/views/games/show.html.erb
<% @all_shots %>

<div class="gamepage">
    <h1> Enemy Board </h1>
     <table>
        <div class="enemy-board">
            <tr>
                <td> </td>
                <td>1</td>
                <td>2</td>
                <td>3</td>
                <td>4</td>
                <td>5</td>
                <td>6</td>
                <td>7</td>
                <td>8</td>
                <td>9</td>
                <td>10</td>
            </tr>

            <% ("A".."J").to_a.each do |row| %>
            <tr class=<%= row %>>
                <td><%= row %></td>
                <% (1..10).to_a.each do |column| %>
                    <% coordinate_id = Coordinate.find_by(row: row, column: column).id %>
                    <% if @all_shots.find_by(player_id: @current_player, coordinate_id: coordinate_id)%>
                        <% if @all_shots.find_by(player_id: @current_player, coordinate_id: coordinate_id).hit == true %>
                            <td class="<%= column %> hit"></td>
                        <% elsif @all_shots.find_by(player_id: @current_player, coordinate_id: coordinate_id).hit == false%>
                            <td class="<%= column %> miss"></td>
                        <% end %>
                    <% else %>
                        <td class=<%= column %>></td>
                    <% end %>
                <% end %>
            </tr>
            <% end %>
        </table>
    </div><br>


    <h1> Friendly Board </h1>
    <table>
        <div class="home-board">
            <tr>
                <td> </td>
                <td>1</td>
                <td>2</td>
                <td>3</td>
                <td>4</td>
                <td>5</td>
                <td>6</td>
                <td>7</td>
                <td>8</td>
                <td>9</td>
                <td>10</td>
            </tr>

            <% ("A".."J").to_a.each do |row| %>
            <tr class=<%= row %>>
                <td><%= row %></td>
                <% (1..10).to_a.each do |column| %>
                    <% coordinate_id = Coordinate.find_by(row: row, column: column).id %>
                    <% if @all_shots.find_by(player_id: @enemy_player, coordinate_id: coordinate_id)%>
                        <% if @all_shots.find_by(player_id: @enemy_player, coordinate_id: coordinate_id).hit == true %>
                            <td class="<%= column %> hit"></td>
                        <% elsif @all_shots.find_by(player_id: @enemy_player, coordinate_id: coordinate_id).hit == false%>
                            <td class="<%= column %> miss"></td>
                        <% end %>
                    <% else %>
                        <td class=<%= column %>></td>
                    <% end %>
                <% end %>
            </tr>
            <% end %>
        </table>
    </div>
    <br>
    <div class="shotform">
        <%= form_for [@game, @coordinate], :url => game_shots_path(@game, @coordinate) do |f| %>
            <%= f.text_field :row, placeholder: "Input Row" %><br><br>
            <%= f.text_field :column, placeholder: "Input Column"  %><br><br>
            <%= f.submit "Fire!" %>
        <% end %>
    </div>
</div><br>

<input type="hidden" id="game_id" value="<%= @game.id %>">

liamship/app/views/games/winner.html.erb
<center><h1 style="color: black; font-size:100px">You Both Won.</h1><center>